# Generated by Django 4.1.3 on 2023-03-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0003_tranactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="tranactions",
            name="acc_no",
            field=models.CharField(default="", max_length=20),
        ),
    ]
