# Generated by Django 4.1.3 on 2023-03-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0004_tranactions_acc_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="tranactions",
            name="status",
            field=models.CharField(default="", max_length=2),
        ),
    ]
