# Generated by Django 4.1.7 on 2023-03-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0007_alter_tranactions_balance_history"),
    ]

    operations = [
        migrations.RemoveField(model_name="tranactions", name="balance_history",),
    ]
