# Generated by Django 4.1.7 on 2023-03-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0008_remove_tranactions_balance_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="tranactions",
            name="balance_histort",
            field=models.CharField(default=0, max_length=14),
        ),
    ]
