# Generated by Django 4.1.7 on 2023-03-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0009_tranactions_balance_histort"),
    ]

    operations = [
        migrations.RemoveField(model_name="tranactions", name="balance_histort",),
    ]
